name: Build Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to ECR Public registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Challenge
          push: true
          tags: |
            public.ecr.aws/l6l3i2k4/pacer-test:latest
        env:
          ECR_REGISTRY: public.ecr.aws/l6l3i2k4