# Generated by Django 4.2 on 2023-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0001_initial'),
    ]

    # Task 3: Database Migration
    operations = [
        migrations.RemoveField(
            model_name='Score',
            name='user_id'
        ),
    ]
